import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Catalog Navigator",
  description: "Generated by Firebase Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        />
        <style>{`
          .modern-card {
            transition: box-shadow 0.3s, transform 0.3s;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            border-radius: 1rem;
          }
          .modern-card:hover {
            box-shadow: 0 8px 24px rgba(0,0,0,0.18);
            transform: translateY(-4px) scale(1.02);
          }
          .modern-btn {
            transition: background 0.2s, transform 0.2s;
          }
          .modern-btn:hover {
            background: linear-gradient(90deg,#2563eb,#38bdf8);
            color: #fff;
            transform: scale(1.05);
          }
        `}</style>
      </head>
      <body className="font-body antialiased h-full">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
